### ISSUE TITLE
codegen non-web-safe tagged templates as function calls in web safe codegen

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-java#116]
``` js
var a = tag`</script>`;
```

should become

``` js
var a = (function(){
  var literalParts = ["</\x73cript>"], computedParts = [];
  literalParts.raw = ["</\x73cript>"];
  return tag.apply(null, [literalParts].concat(computedParts));
}());
```

😞

**Comment by bakkot** [comment]
This might be best (in the sense of "most cleanly", not "fastest") implemented as a reducer which transforms a program into an approximately equivalent form which will codegen safely.

**Comment by bakkot** [comment]
Also, `this` in the tag function is as it would be for a regular call - so if the tag is a MemberExpression, the base object needs to be saved and provided as the first argument to `apply`. Otherwise the first argument should be `undefined` (not `null`).

**Comment by bakkot** [comment]
Actually, I don't think you can make this work with `apply`:

``` js
function f() {
  console.log(this);
}

let o = {};

with (o) {
  f`</script>`; // `this` is global object
}

o.f = f;

with (o) {
  f`</script>`; // `this` is o
}
```

## 

This is possible in an environment which supports spread:

``` js
f(literalParts, ...computedParts)
```

but I don't think you can fake it otherwise.

**Comment by michaelficarra** [comment]
Additionally, the `literalParts` in the original example must be eternal, which it wouldn't be. Instead of the alternate output suggested above, we should just throw in these cases.
