### ISSUE TITLE
CodeGen does not string escape "default" keyword in static property names.

### ISSUE THREAD

**Issue by Protryon** [shapesecurity/shift-java#215]
In module code, it is illegal to have a `default` identifier, and as such, a static property name much be encoded as such: `{"default": ...}` vs `{default: ...}`.

**Comment by bakkot** [comment]
> In module code, it is illegal to have a `default` identifier

`default` is illegal as an `Identifier`, but not an `IdentifierName` (and this is not affected by strictness or whether you're in a module). That is, it's always illegal to have `var default`, but never to have `({ default: 0 })`.

I do not believe properties named `default` ever require encoding in modern JS.

**Comment by michaelficarra** [comment]
@Protryon What test262 test prompted this?
