### ISSUE TITLE
ClassName declarations are considered block scoped, when they are function scoped.

### ISSUE THREAD

**Issue by Protryon** [shapesecurity/shift-java#238]
The effect of this causes `class test {}; new test();` to create two variables, one declared by the class's `BindingIdentifier`, and another declared the same and referenced in the parent scope. This causes unexpected failure as shown in the following test:

```
Script script = Parser.parseScript("class test {}; new test();");
ScopeLookup lookup = new ScopeLookup(ScopeAnalyzer.analyze(script));
ClassDeclaration clas = (ClassDeclaration) script.statements.maybeHead().fromJust();
NewExpression newExpression = (NewExpression) ((ExpressionStatement) script.statements.maybeLast().fromJust()).expression;
assertEquals(lookup.findVariableDeclaredBy(clas.name).fromJust(), lookup.findVariableReferencedBy((IdentifierExpression) newExpression.callee));
```

**Comment by bakkot** [comment]
I can't tell from your sample what the issue is. However, it's correct that there are two variables created. Test:

```js
class A { static m(){ return A; } }; let foo = A; A = 0; foo.m(); // prints the class, not 0
```

**Comment by Protryon** [comment]
@bakkot I see. The issue seems to be that ScopeLookup can only provide one `Variable` per `BindingIdentifier` within . We could either merge `ClassName` and `ClassDeclaration`, as both function and block scoped, or do a breaking change to allow multiple variables to be returned by `findVariableDeclaredBy`, or add a new method to allow returning multiple.

**Comment by bakkot** [comment]
@Protryon:

> add a new method to allow returning multiple

I think we [already have such a method](https://github.com/shapesecurity/shift-java/blob/a34dc7c0b1484e74491e10bfa6e370d678335e15/src/main/java/com/shapesecurity/shift/es2017/scope/ScopeLookup.java#L121).

**Comment by Protryon** [comment]
@bakkot Works for me.
