### ISSUE TITLE
Gradle support for es2018?

### ISSUE THREAD

**Issue by sengiv** [shapesecurity/shift-java#253]
Gradle dependency for es2018 doesn't work
compile group: 'com.shapesecurity', name: 'es2018'

**Comment by michaelficarra** [comment]
I believe "group" is supposed to be `com.shapesecurity.shift`. But es2018 hadn't yet been published. I'll do so as soon as #255 is merged.

**Comment by michaelficarra** [comment]
@sengiv It is published now. Thanks for the report!
