### ISSUE TITLE
Add source offsets

### ISSUE THREAD

**Issue by zmeggyesi** [shapesecurity/shift-java#256]
We'd like to add a new feature that provides the source offsets for nodes (byte-, as well as character-offset). 

Reasoning: our service needs to be able to replace specific portions of the script's string representation, based on unambiguous addressing from AST.

If we were to implement such an offset data, can we expect it to be available in future versions as well?

**Comment by bakkot** [comment]
Is [`ParserWithLocation`](https://github.com/shapesecurity/shift-java/blob/es2018/src/main/java/com/shapesecurity/shift/es2018/parser/ParserWithLocation.java) insufficient?

(It's not as well documented as it should be, but basically you do `ParserWithLocation parser = new ParserWithLocation(); Script script = parser.parseScript(whatever); [...] SourceSpan location = parser.getLocation(node);`.)
