### ISSUE TITLE
Shall we stop caching the result of `Monoid.identity()` in the `MonoidalReducer`?

### ISSUE THREAD

**Issue by ikarienator** [shapesecurity/shift-java#43]
The way the current `ReducerP` is constructed is that all the state will have only one reference globally unless the user intentionally save it somewhere. It shows the possibility to treat the states linear typed and it will be a natural optimization to allow mutation in the object. But `MonoidalReducer` is caching the same empty object and using it everywhere. It prevent people to write bug-resistant mutational code and degrades performance.

**Comment by michaelficarra** [comment]
This is done.
