### ISSUE TITLE
`codegen` code formatting options

### ISSUE THREAD

**Issue by drom** [shapesecurity/shift-java#77]
I can find any description of code formatting capabilities in the `codegen` API. Are there any?
https://github.com/shapesecurity/shift-java/tree/es6/src/main/java/com/shapesecurity/shift/codegen

**Comment by michaelficarra** [comment]
It seems not to be documented, but see the additional `codeGen` interface that has a second boolean `pretty` parameter: https://github.com/shapesecurity/shift-java/blob/bc9df039b7941c61b2140bba42a2a31c4c8d9bf4/src/main/java/com/shapesecurity/shift/codegen/CodeGen.java#L55.
