### ISSUE TITLE
A few of the attributes are not compliant to their lexical order

### ISSUE THREAD

**Issue by ikarienator** [shapesecurity/shift-java#84]
When I'm trying to parse ES5 with parser combinator, the inversed order is really annoying.
For example, when I parse `ObjectProperty`, I will first parse `propertyName` before I parse the expression, but `DataProperty` put the `expression` before the name.

It is useless to particularly define the order in an unnatural order, please fix it.

**Comment by bakkot** [comment]
Fixed in ES2016 (see shapesecurity/shift-spec@e563c5c).
